#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROUTES_FILE = ROOT / "_governance" / "ROUTES.json"
IGNORED_DIRS = {".git", "__pycache__", ".pytest_cache", ".venv", "venv"}
IGNORED_FILES = {".DS_Store"}

def load_routes():
    return json.loads(ROUTES_FILE.read_text(encoding="utf-8"))["routes"]

def repo_files():
    result = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if any(part in IGNORED_DIRS for part in rel.parts):
            continue
        if rel.name in IGNORED_FILES:
            continue
        result.append(rel.as_posix())
    return sorted(result)

def render_master(routes):
    lines = [
        "<!-- GENERATED by scripts/sync_indexes.py. Do not edit manually. -->",
        "# MASTER INDEX — LANCAMENTO",
        "",
        "Índice humano das rotas canônicas. A fonte de verdade é `_governance/ROUTES.json`.",
        "",
        "| Código | Área | Rota | Status |",
        "|---|---|---|---|",
    ]
    for route in routes:
        lines.append(f"| {route['code']} | {route['title']} | `{route['path']}` | {route['status']} |")
    lines += [
        "",
        "Para saber o conteúdo atual de cada rota, consulte `REPOSITORY_MAP.md`.",
        "",
    ]
    return "\n".join(lines)

def render_map(routes, files):
    route_paths = [route["path"] for route in routes]
    controls = [
        f for f in files
        if not any(f == path or f.startswith(path + "/") for path in route_paths)
    ]
    lines = [
        "<!-- GENERATED by scripts/sync_indexes.py. Do not edit manually. -->",
        "# REPOSITORY MAP — LANCAMENTO",
        "",
        "Inventário do estado atual do repositório.",
        "",
        "## Control plane",
        "",
    ]
    for item in controls:
        lines.append(f"- `{item}`")
    for route in routes:
        prefix = route["path"] + "/"
        domain_files = [f[len(prefix):] for f in files if f.startswith(prefix)]
        lines += ["", f"## {route['code']} — {route['title']}", "", f"Rota: `{route['path']}`", ""]
        if domain_files:
            for item in domain_files:
                lines.append(f"- `{item}`")
        else:
            lines.append("- _(sem arquivos)_")
    lines.append("")
    return "\n".join(lines)

def sync(path, expected, check):
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if check:
        if current != expected:
            raise SystemExit(f"Índice desatualizado: {path.relative_to(ROOT)}. Execute: python scripts/sync_indexes.py")
    elif current != expected:
        path.write_text(expected, encoding="utf-8")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    routes = load_routes()
    files = repo_files()
    sync(ROOT / "MASTER_INDEX.md", render_master(routes), args.check)
    sync(ROOT / "REPOSITORY_MAP.md", render_map(routes, files), args.check)
    print("indexes: ok" if args.check else "indexes: synchronized")

if __name__ == "__main__":
    main()
